#!/bin/sh
# gen-llm-targets.sh — Generate Prometheus file_sd targets for LLM node
# Called by cli.sh obs-up before starting observability stack.
# Reads ACER_HOST from environment (set in .env or manually).
#
# Output files:
#   llm-node-targets.yml        — node-exporter :9100
#   llm-node-probe-targets.yml  — blackbox HTTP probe :8080/health

set -e

PROMETHEUS_DIR="$(dirname "$0")"
ACER_HOST="${ACER_HOST:-192.168.100.6}"

cat > "${PROMETHEUS_DIR}/llm-node-targets.yml" << EOF
# Auto-generated by gen-llm-targets.sh — do not edit manually
# Regenerated on: $(date -u +%Y-%m-%dT%H:%M:%SZ)
- targets:
    - "${ACER_HOST}:9100"
  labels:
    job: llm-node
    host: llm-node
    component: hdtv
    instance: "${ACER_HOST}:9100"
EOF

cat > "${PROMETHEUS_DIR}/llm-node-probe-targets.yml" << EOF
# Auto-generated by gen-llm-targets.sh — do not edit manually
# Regenerated on: $(date -u +%Y-%m-%dT%H:%M:%SZ)
- targets:
    - "http://${ACER_HOST}:8080/health"
  labels:
    job: blackbox-http
    component: hdtv
    host: llm-node
EOF

echo "  Generated LLM node targets for Prometheus file_sd:"
echo "    node-exporter: ${ACER_HOST}:9100"
echo "    blackbox probe: http://${ACER_HOST}:8080/health"
