#!/bin/sh
# =============================================================================
# docker-entrypoint.sh — Ansible Runner entrypoint
# =============================================================================
# 1. Reads ACER_HOST / ACER_USER / ACER_SSH_PORT from environment (.env via
#    docker compose) — no hardcoded values anywhere in this file.
# 2. Generates /tmp/inventory.ini dynamically at runtime.
# 3. Copies the SSH key from the Docker secret mount and enforces chmod 600.
# 4. Runs: ansible-playbook -i /tmp/inventory.ini <playbook> [extra args]
# =============================================================================
set -e

# ---------------------------------------------------------------------------
# 1. Validate required env vars — fail early with a clear message
# ---------------------------------------------------------------------------
_missing=""
for _var in ACER_HOST ACER_USER; do
  eval _val=\$$_var
  [ -z "$_val" ] && _missing="${_missing}  • ${_var}\n"
done

if [ -n "$_missing" ]; then
  echo "❌  Missing required environment variables:"
  printf "$_missing"
  echo ""
  echo "    Set them in .env or pass via -e:"
  echo "    docker compose run -e ACER_HOST=x.x.x.x -e ACER_USER=myuser \\"
  echo "      ansible-runner site.yml"
  exit 1
fi

ACER_SSH_PORT="${ACER_SSH_PORT:-22}"

# ---------------------------------------------------------------------------
# 2. Generate dynamic inventory
# ---------------------------------------------------------------------------
INVENTORY=/tmp/inventory.ini
cat > "$INVENTORY" <<EOF
# Auto-generated by docker-entrypoint.sh — do not edit manually.
# Source: ACER_HOST=${ACER_HOST}, ACER_USER=${ACER_USER}, port=${ACER_SSH_PORT}

[acer]
acer-host ansible_host=${ACER_HOST} ansible_user=${ACER_USER} ansible_port=${ACER_SSH_PORT} ansible_ssh_private_key_file=/tmp/ansible_runner_key

[acer:vars]
ansible_python_interpreter=/usr/bin/python3
EOF

echo "▶  Inventory:"
cat "$INVENTORY"
echo ""

# ---------------------------------------------------------------------------
# 3. SSH key — injected via Docker secret at /run/secrets/prod_key
# ---------------------------------------------------------------------------
KEY_SRC="/run/secrets/prod_key"
KEY_DST="/tmp/ansible_runner_key"

if [ -f "$KEY_SRC" ]; then
  cp "$KEY_SRC" "$KEY_DST"
  chmod 600 "$KEY_DST"
  export ANSIBLE_PRIVATE_KEY_FILE="$KEY_DST"
  echo "▶  SSH key loaded from Docker secret → $KEY_DST"
else
  # Fallback: try the key baked into the image at build time
  BAKED_KEY="/ansible/.ssh/prod_key"
  if [ -f "$BAKED_KEY" ]; then
    cp "$BAKED_KEY" "$KEY_DST"
    chmod 600 "$KEY_DST"
    export ANSIBLE_PRIVATE_KEY_FILE="$KEY_DST"
    echo "▶  SSH key loaded from image (.ssh/prod_key) → $KEY_DST"
  else
    echo "⚠️  No SSH key found at ${KEY_SRC} or ${BAKED_KEY}."
    echo "   Running without key — ensure Acer allows password auth or add .ssh/prod_key"
  fi
fi

# Pre-scan Acer host key → prevents interactive 'yes/no' prompt
if [ -n "${ANSIBLE_PRIVATE_KEY_FILE:-}" ] && [ -n "$ACER_HOST" ]; then
  echo "▶  Pre-scanning Acer host key (ssh-keyscan)..."
  ssh-keyscan -p "${ACER_SSH_PORT}" -H "${ACER_HOST}" >> /root/.ssh/known_hosts 2>/dev/null || true
  echo "▶  Host key cached — no interactive prompts."
fi

# ---------------------------------------------------------------------------
# 4. Ansible settings
# ---------------------------------------------------------------------------
export ANSIBLE_HOST_KEY_CHECKING="${ANSIBLE_HOST_KEY_CHECKING:-False}"
export ANSIBLE_FORCE_COLOR="${ANSIBLE_FORCE_COLOR:-1}"

# ---------------------------------------------------------------------------
# 5. Run the playbook
# ---------------------------------------------------------------------------
PLAYBOOK="${1:-site.yml}"
shift || true   # pass remaining args through to ansible-playbook

echo "▶  ansible-playbook -i ${INVENTORY} /ansible/${PLAYBOOK} $*"
echo "══════════════════════════════════════════════════"
exec ansible-playbook \
  -i "$INVENTORY" \
  "/ansible/${PLAYBOOK}" \
  "$@"
