#!/bin/sh
# =============================================================================
# docker-entrypoint.sh — Ansible Runner entrypoint
# =============================================================================
# T-55: Dual-user model — kết nối tutinhhao, become root khi cần.
#
# Prerequisites (bạn làm thủ công 1 lần trên Ubuntu server):
#   - Inject prod_deployer.pub vào /home/tutinhhao/.ssh/authorized_keys  ✅ DONE
#   - Inject prod_deployer.pub vào /root/.ssh/authorized_keys  ✅ DONE
#   - tutinhhao có sudo NOPASSWD (hoặc bootstrap sẽ thiết lập)
#
# Key: .ssh/prod_deployer (ed25519, deployer@prod)
#
# Flow:
#   1. Validate required env vars (ACER_HOST)
#   2. Install SSH private key tại /root/.ssh/prod_deployer
#   3. Generate /tmp/inventory.ini (ansible_user=tutinhhao)
#   4. Generate /tmp/group_vars/acer.yml (become=true, sudo)
#   5. Run: ansible-playbook -i /tmp/inventory.ini <playbook> [extra args]
# =============================================================================
set -e

# ---------------------------------------------------------------------------
# 1. Validate required env vars
# ---------------------------------------------------------------------------
_missing=""
for _var in ACER_HOST; do
  eval _val=\$$_var
  [ -z "$_val" ] && _missing="${_missing}  • ${_var}\n"
done

if [ -n "$_missing" ]; then
  echo "❌  Missing required environment variables:"
  printf "$_missing"
  echo ""
  echo "    Set them in .env or pass via -e:"
  echo "    docker compose run -e ACER_HOST=x.x.x.x ansible-runner site.yml"
  exit 1
fi

ACER_SSH_PORT="${ACER_SSH_PORT:-22}"

# ---------------------------------------------------------------------------
# 2. SSH private key — absolute path, priority: Docker secret > baked image
# ---------------------------------------------------------------------------
KEY_DST="/root/.ssh/prod_deployer"
KEY_SRC="/run/secrets/prod_deployer"
BAKED_KEY="/ansible/.ssh/prod_deployer"

mkdir -p /root/.ssh
chmod 700 /root/.ssh

if [ -f "$KEY_SRC" ]; then
  cp "$KEY_SRC" "$KEY_DST"
  chmod 600 "$KEY_DST"
  echo "▶  SSH key loaded from Docker secret → $KEY_DST"
elif [ -f "$BAKED_KEY" ]; then
  cp "$BAKED_KEY" "$KEY_DST"
  chmod 600 "$KEY_DST"
  echo "▶  SSH key loaded from image ($BAKED_KEY) → $KEY_DST"
else
  echo "❌  No SSH private key found at ${KEY_SRC} or ${BAKED_KEY}."
  echo "    Mount via Docker secret hoặc add .ssh/prod_deployer vào build context."
  exit 1
fi

export ANSIBLE_PRIVATE_KEY_FILE="$KEY_DST"

# ---------------------------------------------------------------------------
# 3. Generate dynamic inventory
#    T-55: ansible_user=tutinhhao (NOT root)
#    become/sudo config in group_vars
# ---------------------------------------------------------------------------
INVENTORY=/tmp/inventory.ini
mkdir -p /tmp/group_vars

cat > "$INVENTORY" <<EOF
# Auto-generated by docker-entrypoint.sh — do not edit manually.
# T-55: Kết nối tutinhhao → become root khi cần.
# ACER_HOST=${ACER_HOST}, port=${ACER_SSH_PORT}

[acer]
acer-host ansible_host=${ACER_HOST} ansible_port=${ACER_SSH_PORT} ansible_ssh_private_key_file=${KEY_DST}
EOF

# ---------------------------------------------------------------------------
# 4. Generate group_vars with become config
# ---------------------------------------------------------------------------
cat > /tmp/group_vars/acer.yml <<EOF
---
# Auto-generated by docker-entrypoint.sh
# T-55: tutinhhao + become root
ansible_python_interpreter: /usr/bin/python3
ansible_user: tutinhhao
ansible_become: true
ansible_become_user: root
ansible_become_method: sudo
$(if [ -n "${HF_TOKEN:-}" ]; then echo "llm_hf_token: \"${HF_TOKEN}\""; fi)
EOF

echo "▶  Inventory:"
cat "$INVENTORY"
echo ""

# Pre-scan host key để tránh interactive yes/no prompt
if [ -n "$ACER_HOST" ]; then
  echo "▶  Pre-scanning host key (ssh-keyscan)..."
  ssh-keyscan -p "${ACER_SSH_PORT}" -H "${ACER_HOST}" >> /root/.ssh/known_hosts 2>/dev/null || true
  echo "▶  Host key cached."
fi

# ---------------------------------------------------------------------------
# 5. Ansible settings
# ---------------------------------------------------------------------------
export ANSIBLE_HOST_KEY_CHECKING="${ANSIBLE_HOST_KEY_CHECKING:-False}"
export ANSIBLE_FORCE_COLOR="${ANSIBLE_FORCE_COLOR:-1}"

# ---------------------------------------------------------------------------
# 6. Run the playbook
# ---------------------------------------------------------------------------
PLAYBOOK="${1:-site.yml}"
shift || true

echo "▶  ansible-playbook -i ${INVENTORY} /ansible/${PLAYBOOK} $*"
echo "══════════════════════════════════════════════════"
exec ansible-playbook \
  -i "$INVENTORY" \
  "/ansible/${PLAYBOOK}" \
  "$@"
